CXXFLAGS=-std=gnu++17 -I universal/include # change accordingly
LDFLAGS=-lquadmath -lgmpxx -lgmp # quadmath is for 128 bit floats

all: float-to-posit posit-uint-to-str

clean:
	rm -rf float-to-posit posit-uint-to-str